FROM ttbb/base

LABEL maintainer="shoothzj@gmail.com"

WORKDIR /opt/sh/minio

RUN wget https://dl.min.io/server/minio/release/linux-amd64/minio && \
chmod +x /opt/sh/minio

ENV MINIO_HOME /opt/sh/minio
