apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-mysql-producer
  labels:
    app: pf-mysql-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pf-mysql-producer
  template:
    metadata:
      labels:
        app: pf-mysql-producer
    spec:
      containers:
      - name: pf-mysql-producer
        image: ttbb/java-demo:mysqlPfProducer
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 4G
            cpu: 1000m
          requests:
            memory: 4G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: KAFKA_ADDR
          value: "kafka-0.kafka:9092,kafka-1.kafka:9092"  
        - name: TOPIC
          value: "test"  
        - name: test
          value: "test"                  