global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 20s
  external_labels:
    cluster: "default"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "pulsar"
    dns_sd_configs:
      - names:
          - "pulsar.com"
        type: 'A'
        port: 8080
        refresh_interval: 10s