bash publish-base.sh
bash publish-apollo.sh
bash publish-bookkeeper.sh
bash publish-cassandra.sh
bash publish-chronograf.sh
bash publish-clickhouse.sh
bash publish-compile.sh
bash publish-coredns.sh
bash publish-druid.sh
bash publish-elasticsearch.sh
bash publish-grafana.sh
bash publish-nginx.sh
bash publish-other.sh
bash publish-python.sh