# docker run -it ttbb/vscode:nake bash
# docker run -p 80:80 -it ttbb/vscode:nake bash
FROM ttbb/base

LABEL maintainer="shoothzj@gmail.com"

RUN curl -fsSL https://code-server.dev/install.sh | sh

WORKDIR /opt/sh