apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-kafka-consumer
  labels:
    app: pf-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pf-kafka-consumer
  template:
    metadata:
      labels:
        app: pf-kafka-consumer
    spec:
      containers:
      - name: pf-kafka-consumer
        image: ttbb/java-demo:kafkaPfConsumer
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 2G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: KAFKA_ADDR
          value: "kafka-0.kafka:9092,kafka-1.kafka:9092"  
        - name: TOPIC
          value: "test"  
        - name: test
          value: "test"                  